# Generated by Django 2.2.15 on 2020-08-25 13:11

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('end_time', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=17, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=16, max_digits=19, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('fcm_id', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=16, max_digits=19, null=True)),
                ('fb_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Normal', max_length=50)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('unread_records_one', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('unread_records_two', models.CharField(default='0', max_length=10)),
                ('unread_records_three', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('verified', models.CharField(default='0', max_length=1)),
                ('privacy_policy', models.CharField(default='0', max_length=1)),
                ('must_change_password', models.CharField(default='0', max_length=1)),
                ('badge', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('login_times', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invite_code', models.CharField(default='0', max_length=6)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='userweight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True)),
                ('body_fat', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新時間')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diabetes.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='userbloodsugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True)),
                ('timeperiod', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新時間')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diabetes.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='userblood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.FloatField(default=0, max_length=3, null=True)),
                ('diastolic', models.FloatField(default=0, max_length=3, null=True)),
                ('pulse', models.CharField(default=0, max_length=3, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新時間')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diabetes.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=15, primary_key=True, serialize=False)),
                ('user_id', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('after_recording', models.CharField(default='0', max_length=1)),
                ('no_recording_for_a_day', models.CharField(default='0', max_length=1)),
                ('over_max_or_under_min', models.CharField(default='0', max_length=1)),
                ('after_meal', models.CharField(default='0', max_length=1)),
                ('unit_of_sugar', models.CharField(default='0', max_length=1)),
                ('unit_of_weight', models.CharField(default='0', max_length=1)),
                ('unit_of_height', models.CharField(default='0', max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diabetes.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='receivemod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atype', models.CharField(max_length=25, null=True)),
                ('accept_or_not', models.CharField(max_length=1, null=True)),
                ('areceive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areceive_user', to='diabetes.Patient')),
                ('breceive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breceive_user', to='diabetes.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='notificationmod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=25, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新時間')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diabetes.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=15, primary_key=True, serialize=False)),
                ('user_id', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('diabetes_type', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('oad', models.CharField(default='0', max_length=1)),
                ('insulin', models.CharField(default='0', max_length=1)),
                ('anti_hypertensives', models.CharField(default='0', max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diabetes.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='friendmod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atype', models.CharField(max_length=25, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('afriend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_user', to='diabetes.Patient')),
                ('bfriend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relay_to_user', to='diabetes.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('type', models.CharField(default='0', max_length=1)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diabetes.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='dietmod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('meal', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True)),
                ('tag', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('image', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新時間')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diabetes.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Default',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=15, primary_key=True, serialize=False)),
                ('user_id', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('sugar_delta_max', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('sugar_delta_min', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('sugar_morning_max', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('sugar_morning_min', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('sugar_evening_max', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('sugar_evening_min', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('sugar_before_max', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('sugar_before_min', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('sugar_after_max', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('sugar_after_min', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('systolic_max', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('systolic_min', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('diastolic_max', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('diastolic_min', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('pulse_max', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('pulse_min', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('weight_max', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('weight_min', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('bmi_max', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('bmi_min', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('body_fat_max', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('body_fat_min', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diabetes.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=25, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新時間')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diabetes.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='A1cs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('a1c', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diabetes.Patient')),
            ],
        ),
    ]
