# Generated by Django 2.2.14 on 2020-07-23 07:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailauth',
            old_name='username',
            new_name='patient',
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=15, primary_key=True, serialize=False)),
                ('user_id', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('diabetes_type', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('oad', models.CharField(default='0', max_length=1)),
                ('insulin', models.CharField(default='0', max_length=1)),
                ('anti_hypertensives', models.CharField(default='0', max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diabetes.Patient')),
            ],
        ),
    ]
