# Generated by Django 2.2.14 on 2020-07-23 08:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0002_auto_20200723_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=15, primary_key=True, serialize=False)),
                ('user_id', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('type', models.CharField(default='0', max_length=1)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diabetes.Patient')),
            ],
        ),
    ]
