# Generated by Django 2.2.14 on 2020-07-18 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0002_auto_20200717_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=25)),
                ('end_time', models.DecimalField(decimal_places=0, max_digits=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diabetes.Patient')),
            ],
        ),
    ]
