# Generated by Django 2.2.14 on 2020-07-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0002_auto_20200720_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
