# Generated by Django 2.2.14 on 2020-07-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0002_auto_20200721_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='after_meal',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='after_recording',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='no_recording_for_a_day',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='over_max_or_under_min',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='unit_of_height',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='unit_of_sugar',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='unit_of_weight',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True),
        ),
    ]
