# Generated by Django 2.2.14 on 2020-07-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0003_emailauth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailauth',
            old_name='token',
            new_name='code',
        ),
    ]
