# Generated by Django 2.2.14 on 2020-07-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0003_drug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
