# Generated by Django 2.2.14 on 2020-07-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0005_a1c'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='A1c',
            new_name='A1cs',
        ),
    ]
